org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric 1.16.5
minecraft_version=1.16.5
loader_version=0.14.25
loader_type=fabric
fabric_version=0.42.0+1.16
modmenu_version=1.16.23

# Mod metadata
mod_id=narcissus_farewell
mod_name=\u6c34\u4ed9\u8f9e(Narcissus Farewell)
mod_license=MIT
mod_version=2.0.0.dev3
mod_group_id=xin.vanilla.narcissus
mod_authors=Tsuki Maaii
mod_description=A configurable teleportation and waypoint utility for servers and optional clients.
sources_url=https://github.com/VanillaXin/NarcissusFarewell_MC
issues_url=https://github.com/VanillaXin/NarcissusFarewell_MC/issues

# Banira Codex public API contract
banira_version=1.0.1
banira_version_range=>=1.0.1 <1.1.0
