# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "${mod_license}"
# A logo to display on the mod's information page, relative to the resources folder.
logoFile = "logo.png"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "${mod_id}" #mandatory
# The version number of the mod
version = "${mod_version}" #mandatory
# A display name for the mod
displayName = "${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
updateJSONURL = "https://update.mc.vanilla.xin/${mod_id}/forge/${minecraft_version}" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://mc.vanilla.xin/narcissus_farewell" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="narcissus_farewell.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors = "${mod_authors}" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''${mod_description}'''
clientRequired = false
# 依赖项 - 使用 .来指示特定 modid 的依赖关系。依赖项是可选的。
[[dependencies."${mod_id}"]] #optional
# 依赖的 Modid
modId = "forge" #mandatory
# 此依赖项是否必须存在 - 如果不存在，则必须指定以下顺序
mandatory = true # 强制的
# 依赖项的版本范围
versionRange = "${forge_version_range}" #mandatory
# 依赖项的排序关系 - 如果依赖项不是必需的，则需要 BEFORE 或 AFTER
# BEFORE - 此 mod 在依赖项之前加载
# AFTER - 此 mod 在依赖项之后加载
ordering = "NONE"
# 此依赖项应用于 BOTH、CLIENT 或 SERVER 的一侧
side = "BOTH"# 这是另一个依赖项
# 依赖配置部分
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
# 此版本范围声明了当前 minecraft 版本的最低版本，但不包括下一个主要版本
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "${mod_id}" # 模组ID
mandatory = true # 模组必须在服务器上安装
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "SERVER" # 强制模组在服务器端运行
[[dependencies."${mod_id}"]]
modId = "${mod_id}" # 模组ID
mandatory = false # 客户端可以不安装
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "CLIENT" # 客户端安装是可选的
